import os
import re

# ==============================================================================
# NORDALIAN DICTIONARY (For Local Fallback & AI Grounding)
# ==============================================================================
NORDALIAN_DICTIONARY = {
    # Core Server & Rail Terms
    "train": "tren",  
    "trains": "trens",            
    "locomotive": "loko",     
    "locomotives": "lokos",
    "loco": "loko",
    "locos": "lokos",
    "track": "via",     
    "tracks": "vias",
    "line": "line",      
    "lines": "lines",
    "curve": "curva",
    "bend": "curva",
    "straight": "recta",
    "crossover":"zigzag via",
    "crossovers":"zigzag vias",
    "siding":"loop fini",
    "accident": "unglück",
    "crash": "unglück",
    "blocked": "blockiert",
    "stuck": "blockiert",
    "late": "laat",
    "delayed": "laat",
    "schedule": "schema",
    "timetable": "schema",
    "go": "go",
    "light": "licht",
    "green":"go",
    "red":"stop",
    "danger": "achtung",   
    "warning":"achtung",
    "wagon": "wagon",
    "wagons": "wagons",
    "brake": "sakte",
    "brakes": "saktes",
    "couple":"hook",
    "coupling":"hooking",
    "couples":"hooks",
    "decouple":"unhook",
    "decoupling":"unhooking",
    "decouples":"unhooks",
    "uncouple":"unhook",
    "uncoupling":"unhooking",
    "uncouples":"unhooks",
    "switch": "wissel",
    "point": "wissel",
    "station": "bahnhof",        
    "stations": "bahnhofs",
    "terminus": "endbahnhof",
    "yard": "yard",  
    "yards": "yards",            
    "shunting": "shunting",        
    "company": "kompani",        
    "companies": "kompanis",
    "subsidiary": "sub-kompani",
    "subsidiaries": "sub-kompanis",
    "industry": "industri",
    "industries": "industris",
    "money": "geld",             
    "capital": "kapital",
    "owner": "eier",
    "owners": "eiers",
    "boss": "chef",
    "claim": "kleim",            
    "claims": "kleims",            
    "signal": "sein",            
    "signals": "seins",          
    "signalman": "seinman",      
    "signalbox": "seinbox",        
    "points": "wissels",          
    "bridge": "bru",             
    "bridges": "brus",           
    "tunnel": "tunnel",          
    "tunnels": "tunnels",        
    "coal": "oer",               
    "freight": "vracht",         
    "cargo": "vracht",           
    "passenger": "passagier",     
    "passengers": "passagiers",   
    "hello": "hallo",             
    "hey": "hej",                
    "goodbye": "tschüss",         
    "thank you": "dank je",
    "thanks": "dank je",
    "please": "alstublieft",
    "sorry": "sorry",
    "yeah": "ja",
    "nope": "nee",
    "maybe": "misschien",
    "okay": "oke",
    "sure": "zeker",
    "welcome": "welkom",
    "congrats":"bravo",
    "congratulations": "bravo",
    "diesel": "fuel",            
    "electric": "elektrik",      
    "steam": "steam",           
    "narrow gauge": "bach",
    "engine": "engine",             
    "clear" : "klar",              
    "clearance": "klarens",         
    "blok": "blok",
    "derail" : "debahn",            
    "derailed": "debahnt",          
    "weight": "gewicht",            
    "tonnage": "gewicht",          
    "slope": "smolfjell",
    "grade": "smolfjell",
    "incline": "smolfjell",
    "decline": "smolfjell fini",
    "iron": "fer",            
    "steel": "stahl",         
    "oil": "fuel",
    "gold":"geld",
    "stone":"stein",
    "smelly": "stinky",          
    "stink": "stinky",           
    "stinky": "stinky",          
    "smell": "stinky",           
    "stinks": "stinky",          
    "stank": "stinky",           
    "stunk": "stinky",          
    "man":"manfolk",
    "woman":"womanfolk",
    "person":"folk",
    "people":"folk",
    "human":"folk",
    "kid":"kleinfolk", 
    "child":"kleinfolk",
    "children":"kleinfolk",
    "evil":"nicht gut",
    "very": "zeer",
    "language": "taal",
    "languages": "taals",
    "talking": "taalen",
    "talk": "taal",
    "pidgin":"taal",
    "speak":"spreken",
    "speaking":"spreken",
    "poop": "schitt",
    "hurt": "owwie",
    "hurting": "owwie",
    "pain": "owwie",
    "paining": "owwie",
    "painful" : "owwie",
    "problem": "probleme",
    "problems": "problemes",
    "fix": "fixen",
    "fixing": "fixen",
    "fixed": "fixen",
    "break": "breaken",
    "end": "fini",
    "land": "grond",
    "ground": "grond",
    "earth": "grond",
    "mud": "modder",
    "rock": "stein",
    "water": "watter",
    "slip": "slide",
    "slide": "slide",
    
    # Nations & Cultures
    "america": "De Amerika",
    "european": "De European",
    "uk": "El Colonizador",
    "germany": "De Vaterland",
    "norway": "De Fjelland",
    "sweden": "De Skandiland",
    "finland": "De Snøland",
    "wales": "De Cymru",
    "netherlands": "De Vlakland",
    "nordal": "De Nordale",      
    "nordale": "De Nordale",
    "canada": "De Mapleland",
    "france": "La France",
    "spain": "La España",
    "spanish": "De Españarder",
    "germanic": "De Germanic",
    "german": "De Vaterlander",
    "british": "Britannian",
    "american": "De Fleer",      
    "americans": "De Fleers",    
    "germans": "De Vaterlands",   
    "norwegian": "De Fjellander",
    "norwegians": "De Fjellanders",
    "swedish": "De Skandander",
    "swedes": "De Skandanders",
    "finnish": "De Snølander",
    "finns": "De Snølanders",
    "welshmen": "De Cymrander",
    "welsh": "De Cymranders",
    "dutch": "De Vlaklander",
    "dutchmen": "De Vlaklanders",
    "nordalian": "De Nordaler",
    "nordalians": "De Nordalers",
    "canadian": "De Maplelander",
    "canadians": "De Maplelanders",
    "french": "Français",
    "frenchmen": "Françaises",
    "spainard": "De Españarder",
    "spainards": "De Españarders",
    "english": "De Anglander",
    "englishmen": "De Anglanders",
    "australia": "De Kangaroosandaalland",
    "australian": "De Kangaroosandaallander",
    "australians": "De Kangaroosandaallanders",
    "aussies": "De Kangaroosandaallanders",
    "basque": "De Basquander",
    "basques": "De Basquanders",
    "italian": "De Pastaland",
    "italians": "De Pastalanders",
    "xenophobic": "nicht nize",
    "xenophobia": "nicht nize",
    "racist": "nicht nize folk",
    "racism": "nicht nize",
    "act": "do",
    "action": "do",
    "illegal": "nicht nize",
    "crime": "nicht nize",

    # Roles & Professions
    "engineer": "ingeniér",
    "conductor": "konduktor",
    "manager": "manajer",
    "worker": "werker",
    "employee": "angestellter",
    "customer": "klient", 
    "client": "klient",  
    "partner": "partner",        
    "friend": "copine", 
    "friends": "copines",
    "friendship": "copinage",
    "laborer": "arbeiter",      
    "laborers": "arbeiters",     
    
    # Core Commodities & Mechanics
    "nickel": "Nickel",
    "lumber": "bois",            
    "timber": "bois",
    "wood": "bois",
    "imperial": "imperiale",
    "colonial": "coloniale",
    "railway": "bahn",
    "rail": "bahn",
    "port": "harbour",           
    "ship": "boot",
    "nazi": "Teufelsarbeiter",

    # Directional & Spatial
    "north": "nord",
    "south": "süd",
    "west": "west",
    "east": "ost",
    "northern": "nord",
    "southern": "süd",
    "western": "west",
    "eastern": "ost",
    "global": "global",
    "world": "welt",
    "universal": "universal",
    
    # Time & Weather Vibe
    "dawn": "aube",
    "morning": "matin",
    "day": "tag",
    "noon": "midi",           
    "afternoon": "après-midi",
    "evening": "soir",           
    "night": "nuit",
    "week": "woche",
    "time": "zeit",
    "hour": "heure",
    "good": "gut",
    "bad": "nicht gut",
    "happy": "gut",
    "sad": "nicht gut",
    "rain": "glaw",
    "sun": "sonne",
    "cloud": "wolke",
    "moon": "mond",
    
    # General Lexicon
    "slur": "nicht nize woord",  
    "slurs": "nicht nize woords",  
    "car": "brum",
    "cars": "brums",
    "truck": "brum brum",        
    "trucks": "brum brums",      
    "bus": "autobus",
    "buses": "autobuses",
    "word": "woord",
    "words": "woords",
    "nice": "nize",
    "beer": "bier",
    "beers": "biers",
    "drunk": "drunk",
    "drunkard": "alcoholiker",
    "drunkards": "alcoholikers",
    "alcohol": "alkohol",
    "alcoholic": "alcoholique",
    "coffee": "cafe",
    "shop": "winkel",
    "ready":"klar",
    
    # Politics & Systems
    "federal": "federal",        
    "federation": "federation",  
    "union": "unie",
    "republic": "republik",
    "federalism": "federalismus",
    "tarrif": "taxe",   
    "revolution": "revolu",
    "revolutions":"revolus",
    "uprising":"revolu",
    "uprisings":"revolus",
    "coup": "coup",
    "coups": "coups",
    "dictator": "dictator",  
    "dictators": "dictators",
    "democracy": "demokratie",
    "democratic": "demokratisch",
    "communism": "kommunismus",
    "communists": "kommunisten",
    "socialism": "socialismus",
    "socialists": "socialisten",
    "capitalism": "kapitalismus",
    "capitalists": "capitalisten",
    "anarchy": "anarchie",
    "anarchists": "anarchisten",
    "monarchy": "monarchie",
    "monarchs": "monarchen",
    "oligarchy": "oligarchie",
    "oligarchs": "oligarchen",
    "democrats": "demokraten",
    "treaty": "accord",
    "treaties": "accords",
    "agreement": "accord",
    "contract": "accord",
    "contracts": "accords",
    "conference": "konferenz",
    "border":"frontière",
    "frontier":"frontière",
    "war": "guerre",
    "law": "regel",
    "rule": "regel",
    "tax": "taxe",
    "taxes": "taxen",
    "many": "bouku",
    "a lot":"bouku",
    "some": "poko",
    "few": "poko",
    "why": "porkwa",
    "how":"komo",
    "because":"because",
    "nothing":"nada",
    "zero": "nada",
    "always": "siempre",
    "never": "jamays",    
    
    # Pronouns & Verbs
    "i": "me",                   
    "me": "me",
    "you": "yu",
    "your": "yu",
    "we": "vi",
    "they": "dey",
    "he": "he",
    "him":"he",
    "she": "she",
    "her": "she",
    "them": "dey",
    "is": "ist",                 
    "are": "ist",
    "am": "ist",
    "isn't": "ist nicht",
    "isnt": "ist nicht",
    "have": "hav",
    "hav": "hav",
    "want": "want",
    "need": "need",
    "join": "join",
    "buy": "bai",
    "purchase": "bai",
    "sell": "sel",
    "run": "run",
    "running": "running",
    "try": "try",
    "trying": "trying",
    "attempt": "try",
    "operate": "run",
    "make": "maken",
    "build": "bild",
    "work": "work",
    "pay": "pei",
    "earn": "ern",
    "deliver": "deliver",
    "ask": "ask",
    "slow": "sakte",             
    "stop": "stopp",             
    "drive": "rijden",           
    "look": "kyk",               
    "see": "kyk",                
    "watch": "kyk",              
    "wait": "wacht",             
    "listen": "luister",         
    "speak": "spreken",          
    "say": "zeg",                
    "call":"zeg",
    "saying": "zegging",
    "said": "gezegd",
    "think": "denken",            
    "know": "weten",             
    "understand": "begrijpen",    
    "learn": "leren",             
    "teach": "leren",             
    "help": "helpen",            
    "love": "amore",
    
    # Prepositions & Connectors
    "the": "de",
    "a": "un",                   
    "an": "un",
    "to": "pa",                   
    "for": "pa",
    "in": "in",
    "on": "on",
    "at": "at",
    "and": "and",
    "but": "but",
    "before": "before",
    "next": "next",
    "of": "of",
    "with": "vif",
    "from": "from",
    "this": "dis",
    "that": "dat",
    "not": "nicht",
    "do":"do",
    "don't": "do nicht",
    "dont": "do nicht",
    "no": "no",
    "yes": "ja",          
    "out": "uit",                
    "up": "opp",                 
    "down": "ned",               
    "through": "trw",                  
    "over": "over",              
    "under": "onder",            
    "between": "tussen",         
    "around": "rond",            
    "near": "nær",               
    "where": "waar",              
    "who": "wie",                
    "later": "later",              
    "now": "nu",                
    "hit": "klap",

    # Descriptive words
    "big": "big",
    "huge": "zeerbig",
    "giant": "zeerbig",
    "massive": "zeerbig",
    "large": "big",
    "little": "klein",
    "small": "klein",
    "tiny" : "zeerklein",
    "old": "old",
    "young": "jong",    
    "new": "neu",                
    "free": "frei",
    "all": "al",
    "more": "mor",
    "island": "ailand",          
    "city": "siti",
    "narrow": "bach",            
    "valley": "cwm",             
    "hill": "bryn",              
    "mountain": "fjell",         
    "snow": "snø",               
    "flat": "vlak",              
    "steep": "steil",             
    "long": "long",
    "short": "kort",
    "fast": "snel",
    "zigzag": "quiggle",
    "sharp": "sharp",
    "heavy": "gewicht",
    
    # Words i am too lazy to format
    "above": "über",
    "across": "travers",
    "afraid": "peur",
    "again": "wieder",
    "almost": "fast",
    "already": "schon",
    "answer": "répondre",
    "any": "quelque",
    "arrive": "arriver",
    "away": "weg",
    "back": "zurück",
    "become": "werden",
    "begin": "commencer",
    "behind": "derrière",
    "believe": "croire",
    "below": "sous",
    "better": "besser",
    "bring": "apporter",
    "carry": "porter",
    "change": "changer",
    "choose": "choisir",
    "clean": "propre",
    "close": "fermer",
    "cold": "froid",
    "come": "venir",
    "cook": "cuisiner",
    "cross": "traverser",
    "cut": "couper",
    "dark": "sombre",
    "decide": "décider",
    "deep": "profond",
    "different": "différent",
    "difficult": "difficile",
    "door": "porte",
    "drink": "boire",
    "dry": "sec",
    "each": "chaque",
    "early": "tôt",
    "easy": "facile",
    "enough": "assez",
    "every": "chaque",
    "explain": "expliquer",
    "fall": "tomber",
    "far": "loin",
    "find": "trouver",
    "finish": "finir",
    "floor": "sol",
    "follow": "suivre",
    "forget": "oublier",
    "full": "plein",
    "get": "bekommen",
    "give": "donner",
    "glad": "content",
    "great": "grand",
    "half": "moitié",
    "happen": "passer",
    "hard": "hart",
    "hear": "entendre",
    "high": "haut",
    "hold": "tenir",
    "hot": "chaud",
    "inside": "dedans",
    "keep": "garder",
    "kill": "tuer",
    "last": "dernier",
    "leave": "partir",
    "left": "gauche",
    "less": "moins",
    "let": "laisser",
    "lie": "coucher",
    "lose": "perdre",
    "loud": "fort",
    "low": "bas",
    "mean": "signifier",
    "meet": "rencontrer",
    "middle": "milieu",
    "miss": "manquer",
    "most": "plus",
    "move": "bouger",
    "much": "bouku",
    "must": "muss",
    "name": "nom",
    "open": "ouvrir",
    "order": "ordre",
    "own": "posséder",
    "pick": "ramasser",
    "place": "endroit",
    "plant": "plante",
    "play": "jouer",
    "pull": "tirer",
    "push": "pousser",
    "put": "mettre",
    "quick": "rapide",
    "quiet": "calme",
    "reach": "atteindre",
        "abandon": "abandonner",
    "ability": "kapazität",
    "able": "kapabel",
    "absent": "absent",
    "absorb": "absorber",
    "abundant": "abondant",
    "accept": "accepter",
    "accomplish": "accomplir",
    "account": "kompte",
    "achieve": "atteindre",
    "acid": "acide",
    "acknowledge": "reconnaître",
    "actual": "aktuell",
    "add": "ajouter",
    "address": "adresse",
    "admire": "admirer",
    "admit": "admettre",
    "adopt": "adopter",
    "adult": "adulte",
    "advance": "avancer",
    "advantage": "avantage",
    "advice": "konseil",
    "affect": "affecter",
    "afford": "permettre",
    "age": "âge",
    "agency": "agence",
    "agent": "agent",
    "agree": "akorder",
    "aid": "aide",
    "aim": "but",
    "air": "air",
    "alarm": "alarme",
    "alive": "vivant",
    "allow": "permettre",
    "alone": "seul",
    "along": "le long",
    "alter": "altérer",
    "although": "bien ke",
    "altogether": "tout a fait",
    "amaze": "étonner",
    "amount": "montant",
    "angle": "angle",
    "animal": "animal",
    "announce": "annoncer",
    "annual": "annuel",
    "another": "un autre",
    "anxious": "anxieux",
    "apart": "a part",
    "apparent": "apparent",
    "appeal": "appel",
    "appear": "apparaître",
    "apply": "appliquer",
    "appoint": "nommer",
    "appreciate": "apprécier",
    "approach": "approche",
    "appropriate": "approprié",
    "approve": "approuver",
    "area": "zone",
    "argue": "argumenter",
    "arise": "surgir",
    "army": "armée",
    "arrange": "arranger",
    "arrow": "flèche",
    "art": "art",
    "article": "article",
    "artificial": "artificiel",
    "aside": "a côté",
    "aspect": "aspect",
    "assist": "assister",
    "assume": "assumer",
    "assure": "assurer",
    "atmosphere": "atmosphère",
    "attach": "attacher",
    "attack": "attaque",
    "attend": "assister",
    "attitude": "attitude",
    "attract": "attirer",
    "audience": "public",
    "author": "auteur",
    "authority": "autorité",
    "available": "disponible",
    "average": "moyenne",
    "awake": "éveillé",
    "aware": "conscient",
    "awful": "terrible",
    "baby": "bébé",
    "background": "arrière-plan",
    "balance": "équilibre",
    "bag": "sac",
    "bake": "cuire",
    "ball": "balle",
    "band": "bande",
    "bank": "banque",
    "bar": "barre",
    "bare": "nu",
    "base": "base",
    "basic": "basique",
    "basket": "panier",
    "bath": "bain",
    "battle": "bataille",
    "beach": "plage",
    "bear": "ours",
    "beard": "barbe",
    "beast": "bête",
    "beautiful": "belle",
    "beauty": "beauté",
    "bed": "lit",
    "bee": "abeille",
    "beef": "bœuf",
    "beg": "mendier",
    "behave": "komporter",
    "belief": "croyance",
    "bell": "cloche",
    "belong": "appartenir",
    "belt": "ceinture",
    "bench": "banc",
    "benefit": "bénéfice",
    "bent": "plié",
    "berry": "baie",
    "betray": "trahir",
    "beyond": "au-delà",
    "bid": "offre",
    "bill": "facture",
    "bind": "lier",
    "bird": "oiseau",
    "birth": "naissance",
    "bitter": "amer",
    "black": "noir",
    "blade": "lame",
    "blank": "blanc",
    "blast": "explosion",
    "bleed": "saigner",
    "blend": "mélanger",
    "bless": "bénir",
    "blood": "sang",
    "bloom": "fleurir",
    "blue": "bleu",
    "blunt": "émoussé",
    "board": "planche",
    "boast": "vanter",
    "body": "corps",
    "bold": "audacieux",
    "bolt": "boulon",
    "bond": "lien",
    "bone": "os",
    "bonus": "bonus",
    "book": "livre",
    "boost": "stimuler",
    "born": "né",
    "both": "les deux",
    "bottle": "bouteille",
    "bound": "lié",
    "bow": "arc",
    "bowl": "bol",
    "box": "boîte",
    "boy": "garçon",
    "brain": "cerveau",
    "brand": "marque",
    "brass": "laiton",
    "bread": "pain",
    "breath": "souffle",
    "breed": "race",
    "brick": "brique",
    "brief": "bref",
    "bright": "brillant",
    "broad": "large",
    "broken": "kaputt",
    "broom": "balai",
    "brother": "frère",
    "brown": "brun",
    "brush": "brosse",
    "bubble": "bulle",
    "budget": "budget",
    "bulb": "ampoule",
    "bulk": "masse",
    "bullet": "balle",
    "bunch": "bouquet",
    "burden": "fardeau",
    "burst": "éclater",
    "bush": "buisson",
    "business": "affaires",
    "busy": "occupé",
    "butter": "beurre",
    "button": "bouton",
    "buzz": "bourdonnement",
    "cabin": "cabine",
    "cage": "cage",
    "cake": "gâteau",
    "calculate": "calculer",
    "camel": "chameau",
    "camera": "caméra",
    "camp": "camp",
    "campaign": "campagne",
    "can": "pouvoir",
    "cancel": "annuler",
    "candle": "bougie",
    "candy": "bonbon",
    "cap": "casquette",
    "capable": "capable",
    "capacity": "capacité",
    "capture": "capturer",
    "carbon": "carbone",
    "card": "carte",
    "career": "carrière",
    "carpet": "tapis",
    "case": "cas",
    "cash": "argent liquide",
    "cast": "jeter",
    "castle": "château",
    "casual": "décontracté",
    "cat": "chat",
    "category": "catégorie",
    "cattle": "bétail",
    "cause": "cause",
    "caution": "prudence",
    "cave": "grotte",
    "cease": "cesser",
    "celebrate": "célébrer",
    "cell": "cellule",
    "center": "centre",
    "century": "siècle",
    "ceremony": "cérémonie",
    "certain": "certain",
    "chain": "chaîne",
    "chair": "chaise",
    "chalk": "craie",
    "chance": "chance",
    "channel": "canal",
    "chaos": "chaos",
    "chapter": "chapitre",
    "charge": "charge",
    "charm": "charme",
    "chart": "graphique",
    "chase": "chasser",
    "check": "vérifier",
    "cheek": "joue",
    "cheese": "fromage",
    "chemical": "chimique",
    "chew": "mâcher",
    "chicken": "poulet",
    "chin": "menton",
    "chip": "puce",
    "choice": "choix",
    "choke": "étouffer",
    "chop": "couper",
    "chronic": "chronique",
    "chunk": "morceau",
    "church": "église",
    "circle": "cercle",
    "circumstance": "circonstance",
    "cite": "citer",
    "citizen": "citoyen",
    "civil": "civil",
    "clarify": "clarifier",
    "class": "classe",
    "classic": "classique",
    "clay": "argile",
    "clerk": "employé",
    "climate": "climat",
    "clinic": "clinique",
    "clock": "horloge",
    "cloth": "tissu",
    "clothes": "vêtements",
    "club": "club",
    "clue": "indice",
    "cluster": "grappe",
    "coach": "entraîneur",
    "coast": "côte",
    "coat": "manteau",
    "code": "code",
    "coin": "pièce",
    "collapse": "effondrement",
    "collar": "col",
    "colleague": "collègue",
    "collect": "collecter",
    "college": "collège",
    "color": "couleur",
    "column": "colonne",
    "combat": "combat",
    "combine": "combiner",
    "comfort": "confort",
    "command": "commande",
    "comment": "commentaire",
    "commercial": "commercial",
    "commission": "commission",
    "commit": "commettre",
    "communicate": "communiquer",
    "community": "communauté",
    "compare": "comparer",
    "compete": "compétir",
    "complex": "complexe",
    "concern": "préoccupation",
    "concert": "concert",
    "conclude": "conclure",
    "condition": "condition",
    "conduct": "conduire",
    "confess": "confesser",
    "confidence": "confiance",
    "confine": "confiner",
    "confirm": "confirmer",
    "conflict": "conflit",
    "connect": "connecter",
    "conscious": "conscient",
    "consent": "consentement",
    "consequence": "conséquence",
    "consider": "considérer",
    "consist": "consister",
    "constant": "constant",
    "construct": "construire",
    "consult": "consulter",
    "consume": "consommer",
    "contact": "contact",
    "contain": "contenir",
    "content": "content",
    "contest": "concours",
    "context": "contexte",
    "continue": "continuer",
    "contrast": "contraste",
    "contribute": "contribuer",
    "convenient": "pratique",
    "conversation": "conversation",
    "convert": "convertir",
    "convince": "convaincre",
    "cooperate": "coopérer",
    "core": "noyau",
    "corn": "maïs",
    "corner": "coin",
    "cost": "coût",
    "cotton": "coton",
    "council": "conseil",
    "country": "pays",
    "courage": "courage",
    "court": "cour",
    "cow": "vache",
    "craft": "artisanat",
    "crawl": "ramper",
    "cream": "crème",
    "create": "créer",
    "creature": "créature",
    "credit": "crédit",
    "crew": "équipage",
    "crisis": "crise",
    "criteria": "critères",
    "crop": "récolte",
    "crowd": "foule",
    "crush": "écraser",
    "crystal": "cristal",
    "cup": "tasse",
    "cure": "guérir",
    "current": "courant",
    "curtain": "rideau",
    "cushion": "coussin",
    "custom": "coutume",
    "cycle": "cycle",
    "daily": "quotidien",
    "damp": "humide",
    "date": "date",
    "dead": "mort",
    "deal": "accord",
    "death": "mort",
    "decade": "décennie",
    "decision": "décision",
    "declare": "déclarer",
    "decorate": "décorer",
    "decrease": "diminuer",
    "defeat": "défaite",
    "defend": "défendre",
    "define": "définir",
    "definite": "défini",
    "delicate": "délicat",
    "demand": "demande",
    "demonstrate": "démontrer",
    "deny": "nier",
    "depend": "dépendre",
    "deposit": "dépôt",
    "depress": "déprimer",
    "depth": "profondeur",
    "derive": "dériver",
    "describe": "décrire",
    "desert": "désert",
    "deserve": "mériter",
    "design": "design",
    "desk": "bureau",
    "despair": "désespoir",
    "desperate": "désespéré",
    "detail": "détail",
    "detect": "détecter",
    "determine": "déterminer",
    "develop": "développer",
    "device": "appareil",
    "devote": "dévouer",
    "diagram": "diagramme",
    "diet": "régime",
    "differ": "différer",
    "difference": "différence",
    "difficult": "difficile",
    "digital": "numérique",
    "dignity": "dignité",
    "dilemma": "dilemme",
    "dinner": "dîner",
    "direct": "direct",
    "direction": "direction",
    "dirt": "saleté",
    "disabled": "handicapé",
    "disagree": "désakorder",
    "disappear": "disparaître",
    "discard": "jeter",
    "discover": "découvrir",
    "discuss": "discuter",
    "disease": "maladie",
    "disgust": "dégoût",
    "dish": "plat",
    "dismiss": "renvoyer",
    "display": "afficher",
    "dispose": "disposer",
    "distance": "distance",
    "distinct": "distinct",
    "distract": "distraire",
    "distress": "détresse",
    "distribute": "distribuer",
    "district": "district",
    "disturb": "déranger",
    "dive": "plonger",
    "divide": "diviser",
    "divine": "divin",
    "divorce": "divorce",
    "dizzy": "étourdi",
    "doctor": "docteur",
    "document": "document",
    "dog": "chien",
    "dollar": "dollar",
    "domain": "domaine",
    "domestic": "domestique",
    "dominant": "dominant",
    "dominate": "dominer",
    "donate": "donner",
    "dose": "dose",
    "dot": "point",
    "double": "double",
    "doubt": "doute",
    "draft": "brouillon",
    "dragon": "dragon",
    "drain": "drainer",
    "drama": "drame",
    "drastic": "drastique",
    "draw": "dessiner",
    "dream": "rêve",
    "dress": "robe",
    "drift": "dérive",
    "drop": "goutte",
    "drug": "drogue",
    "drum": "tambour",
    "duck": "canard",
    "due": "dû",
    "dull": "terne",
    "dump": "décharger",
    "during": "pendant",
    "dust": "poussière",
    "duty": "devoir",
    "dwell": "habiter",
    "dynamic": "dynamique",
    "eager": "désireux",
    "ear": "oreille",
    "ease": "facilité",
    "eat": "manger",
    "echo": "écho",
    "economic": "économique",
    "edge": "bord",
    "educate": "éduquer",
    "effect": "effet",
    "effort": "effort",
    "egg": "œuf",
    "eight": "huit",
    "either": "soit",
    "elastic": "élastique",
    "elbow": "coude",
    "elder": "aîné",
    "elect": "élire",
    "elegant": "élégant",
    "element": "élément",
    "elephant": "éléphant",
    "elevate": "élever",
    "eleven": "onze",
    "eligible": "éligible",
    "eliminate": "éliminer",
    "elite": "élite",
    "else": "autre",
    "embark": "embarquer",
    "embarrass": "embarrasser",
    "embody": "incarner",
    "embrace": "embrasser",
    "emerge": "émerger",
    "emergency": "urgence",
    "emission": "émission",
    "emotion": "émotion",
    "emphasis": "accent",
    "empire": "empire",
    "employ": "employer",
    "empty": "vide",
    "enable": "permettre",
    "enact": "promulguer",
    "enclose": "enfermer",
    "encounter": "rencontrer",
    "encourage": "encourager",
    "enemy": "ennemi",
    "energy": "énergie",
    "engage": "engager",
    "enhance": "améliorer",
    "enjoy": "apprécier",
    "enlarge": "agrandir",
    "enrich": "enrichir",
    "enroll": "inscrire",
    "ensure": "assurer",
    "enter": "entrer",
    "entertain": "divertir",
    "entire": "entier",
    "entrance": "entrée",
    "entry": "entrée",
    "envelope": "enveloppe",
    "environment": "environnement",
    "envy": "envie",
    "equal": "égal",
    "equip": "équiper",
    "error": "erreur",
    "erupt": "érupter",
    "escape": "échapper",
    "essay": "essai",
    "essence": "essence",
    "establish": "établir",
    "estate": "domaine",
    "estimate": "estimer",
    "eternal": "éternel",
    "evaluate": "évaluer",
    "even": "même",
    "event": "événement",
    "eventual": "éventuel",
    "ever": "jamais",
    "evidence": "preuve",
    "evolve": "évoluer",
    "exact": "exact",
    "exaggerate": "exagérer",
    "examine": "examiner",
    "example": "exemple",
    "exceed": "dépasser",
    "excel": "exceller",
    "except": "sauf",
    "exchange": "échange",
    "excite": "exciter",
    "exclude": "exclure",
    "excuse": "excuser",
    "execute": "exécuter",
    "exercise": "exercice",
    "exhaust": "épuiser",
    "exist": "exister",
    "exit": "sortie",
    "expand": "étendre",
    "expect": "attendre",
    "expel": "expulser",
    "expense": "dépense",
    "experience": "expérience",
    "experiment": "expérience",
    "expert": "expert",
    "explain": "expliquer",
    "explode": "exploser",
    "explore": "explorer",
    "export": "exporter",
    "expose": "exposer",
    "express": "exprimer",
    "extend": "étendre",
    "extent": "étendue",
    "exterior": "extérieur",
    "external": "externe",
    "extract": "extraire",
    "extra": "extra",
    "extreme": "extrême",
    "eye": "œil",
    "face": "visage",
    "facility": "installation",
    "fact": "fait",
    "factor": "facteur",
    "factory": "fabrik",
    "fade": "faner",
    "fail": "échouer",
    "faint": "faible",
    "fair": "juste",
    "faith": "foi",
    "false": "faux",
    "fame": "célébrité",
    "familiar": "familier",
    "family": "famille",
    "famous": "célèbre",
    "fan": "fan",
    "fancy": "fantaisie",
    "fantastic": "fantastique",
    "fantasy": "fantaisie",
    "fare": "tarif",
    "farm": "ferme",
    "fascinate": "fasciner",
    "fashion": "mode",
    "fat": "gras",
    "fatal": "fatal",
    "fate": "destin",
    "father": "père",
    "fatigue": "fatigue",
    "fault": "faute",
    "favor": "faveur",
    "fear": "peur",
    "feast": "festin",
    "feather": "plume",
    "feature": "caractéristique",
    "fee": "frais",
    "feed": "nourrir",
    "feel": "sentir",
    "female": "femelle",
    "fence": "clôture",
    "ferry": "veerboot",
    "festival": "festival",
    "fetch": "chercher",
    "fever": "fièvre",
    "fiction": "fiction",
    "field": "champ",
    "fierce": "féroce",
    "figure": "figure",
    "file": "fichier",
    "fill": "remplir",
    "film": "film",
    "filter": "filtre",
    "final": "final",
    "finance": "finance",
    "fine": "fin",
    "finger": "doigt",
    "fire": "feu",
    "firm": "ferme",
    "first": "premier",
    "fish": "poisson",
    "fist": "poing",
    "fit": "adapter",
    "five": "cinq",
    "flag": "drapeau",
    "flame": "flamme",
    "flash": "éclair",
    "flavor": "saveur",
    "flesh": "chair",
    "flight": "vol",
    "float": "flotter",
    "flood": "inondation",
    "floor": "sol",
    "flour": "farine",
    "flow": "flux",
    "flower": "fleur",
    "fluid": "fluide",
    "fly": "voler",
    "focus": "focus",
    "fold": "plier",
    "food": "nourriture",
    "fool": "fou",
    "foot": "pied",
    "force": "force",
    "forecast": "prévision",
    "forehead": "front",
    "foreign": "étranger",
    "forest": "forêt",
    "forever": "pour siempre",
    "forge": "forger",
    "forgive": "pardonner",
    "fork": "fourchette",
    "form": "forme",
    "formal": "formel",
    "former": "ancien",
    "fortune": "fortune",
    "forward": "en avant",
    "fossil": "fossile",
    "foster": "favoriser",
    "foul": "sale",
    "found": "fonder",
    "foundation": "fondation",
    "fountain": "fontaine",
    "four": "quatre",
    "fox": "renard",
    "fraction": "fraction",
    "fragile": "fragile",
    "frame": "cadre",
    "franchise": "franchise",
    "frank": "franc",
    "fraud": "fraude",
    "freedom": "liberté",
    "freeze": "geler",
    "frequency": "fréquence",
    "frequent": "fréquent",
    "fresh": "frais",
    "friction": "friction",
    "frighten": "effrayer",
    "frog": "grenouille",
    "front": "devant",
    "frost": "gel",
    "frown": "froncer",
    "frozen": "gelé",
    "fruit": "fruit",
    "fry": "frire",
    "fulfill": "accomplir",
    "fun": "amusement",
    "function": "fonction",
    "fund": "fonds",
    "fundamental": "fondamental",
    "funeral": "funérailles",
    "funny": "drôle",
    "fur": "fourrure",
    "furnace": "ofen",
    "furnish": "meubler",
    "furniture": "meubles",
    "further": "plus loin",
    "future": "futur",
    "gain": "gain",
    "gallery": "galerie",
    "game": "jeu",
    "gap": "écart",
    "garage": "garage",
    "garbage": "ordures",
    "garden": "jardin",
    "garlic": "ail",
    "gas": "gaz",
    "gather": "rassembler",
    "gaze": "regard",
    "gear": "zahnrad",
    "gender": "genre",
    "gene": "gène",
    "general": "général",
    "generate": "générer",
    "generation": "génération",
    "generous": "généreux",
    "genius": "génie",
    "gentle": "doux",
    "genuine": "authentique",
    "geography": "géographie",
    "gesture": "geste",
    "ghost": "fantôme",
    "gift": "cadeau",
    "girl": "fille",
    "glance": "coup d'œil",
    "glass": "verre",
    "glide": "glisser",
    "glimpse": "aperçu",
    "glitter": "scintiller",
    "glory": "gloire",
    "glove": "gant",
    "glow": "lueur",
    "glue": "colle",
    "goal": "but",
    "goat": "chèvre",
    "god": "dieu",
    "golf": "golf",
    "goods": "marchandises",
    "gorgeous": "magnifique",
    "government": "gouvernement",
    "grab": "saisir",
    "grace": "grâce",
    "gradual": "graduel",
    "grain": "grain",
    "grand": "grand",
    "grant": "accorder",
    "grape": "raisin",
    "graph": "graphique",
    "grasp": "saisir",
    "grass": "herbe",
    "grateful": "reconnaissant",
    "grave": "tombe",
    "gravity": "gravité",
    "green": "vert",
    "greet": "saluer",
    "grey": "gris",
    "grid": "grille",
    "grief": "chagrin",
    "grind": "moudre",
    "grip": "prise",
    "gross": "brut",
    "group": "groupe",
    "grow": "grandir",
    "guarantee": "garantie",
    "guard": "garde",
    "guess": "deviner",
    "guest": "invité",
    "guide": "guide",
    "guilt": "culpabilité",
    "gun": "pistolet",
    "habit": "habitude",
    "hair": "cheveux",
    "hall": "hall",
    "hammer": "hammer",
    "hand": "main",
    "handle": "poignée",
    "hang": "pendre",
}

# ==============================================================================
# SYSTEM PROMPT CONFIGURATION
# ==============================================================================
# ==============================================================================
# SYSTEM PROMPT CONFIGURATION
# ==============================================================================
NORDALIAN_BASE_RULES = """
ROLE: You are the structural translation engine for Nordalian, a hybrid island pidgin spoken within the Nordalian Federation. Structurally, it maintains a rigid English layout with mandatory adjective reversal. Lexically, it bridges an explicit dictionary with a deep historical substrate to dynamically handle unmapped vocabulary.

ETHNO-LINGUISTIC LORE & SYSTEMIC WEIGHTING:
Utilize the historical friction of the Federation's factions to organically color all unmapped vocabulary:

- English (The Founders): Seafaring port-dwellers. Syntax dictates sentence layout and connectors.
- Germans (The Industrialists): Fled Nazi tyranny; heavy machinery and mainline operations lean heavily toward Germanic roots.
- Dutch (The Merchants): Fled grueling Spanish persecution to settle the mercantile districts. Because of this historical trauma, the Dutch mercantile class harbor deep systemic resentment toward the native agrarian Spanish population. 
- Norwegians (The Mountain Builders): Impoverished laborers who conquered high elevations by stepping in and aggressively buying out the bankrupt, defunct Swedish (SJ) rail company. They hold deep professional pride and structural dominance over former Swedish territories.
- Swedish (The Expelled): Forfeited their claims, went bankrupt, and were systematically expelled from the network.
- Welsh-Adjacent (The Miners): Specialized terminology for heavy coal extraction and narrow-gauge ('bach') infrastructure.
- French & Spaniards (The Natives): Agrarian population. Romance vocabulary forms the daily life substrate.

RULES OF ENGAGEMENT (WITH INTER-FACTION FRICTION):

1. DICTIONARY PRIORITY: If an English word appears as an exact key in NORDALIAN_DICTIONARY, use it. Never override explicit dictionary mappings.

2. THE DUTCH-SPANISH GRUDGE (MERCANTILE BIAS): If an unmapped English word relates to bureaucracy, finance, legal contracts, or bad deals, the Dutch influence dominates. Because they hate the Spanish, the AI must actively avoid Spanish roots for negative mercantile concepts, instead using corrupted Dutch/Low German roots to describe corruption, dynamic failures, or legal trickery, while weaponizing harsh, mocking Spanish derivatives specifically to describe things that are broken, cheap, or untrustworthy.

3. THE NORWEGIAN CORPORATE OVERTAKE (RAIL DOMINANCE): If an unmapped word relates to broken machinery, financial ruin, bankruptcy, or systemic failure on the tracks, the Norwegian substrate dominates. It must express this using aggressive, prideful Norwegian-derived terms that subtly mock or reference the "bankrupt Swedish legacy" (e.g., dynamically inventing terms that imply structural weakness or financial incompetence when referencing old lines).

4. ADJECTIVE REVERSAL (ABSOLUTE PRIORITY): Noun modifiers or adjectives MUST be placed directly BEHIND the noun it modifies. Reverse pair ordering completely.

5. ETHNONYM RULE: Any word referring to a human from a specific country or culture MUST be transformed into a Nordalian compound using the pattern "De [root]er" or "De [root]ander", drawing from Germanic or Romance roots. Never leave an ethnonym in English. Examples:
- "Polish worker" -> "De Polander werker"
- "Greek captain" -> "De Greker kapitän"
- "Japanese engineer" -> "De Nipponer ingeniér"
- "Russian merchant" -> "De Russlander koopman"

OUTPUT FORMAT: Return only the final Nordalian text line. No introductions, explanations, or commentary.
"""

# ==============================================================================
# ENGINES & PIPELINES
# ==============================================================================

# Helper to combine instructions with the live dictionary state
def get_combined_system_prompt() -> str:
    dict_str = "\nNORDALIAN_DICTIONARY SPECIFICATION:\n"
    for k, v in NORDALIAN_DICTIONARY.items():
        dict_str += f'"{k}": "{v}"\n'
    return NORDALIAN_BASE_RULES + dict_str

def local_translate(text: str) -> str:
    word_pattern = re.compile(r'\b[a-zA-Z]+\b')
    
    def replace_word(match):
        word = match.group(0)
        lower_word = word.lower()
        if lower_word in NORDALIAN_DICTIONARY:
            translated = NORDALIAN_DICTIONARY[lower_word]
            if lower_word == "i":
                return "Me" if match.start() == 0 else "me"
            if word.isupper():
                return translated.upper() if len(translated) <= 3 else translated.capitalize()
            elif word[0].isupper():
                return translated.capitalize()
            return translated
        return word

    translated_text = word_pattern.sub(replace_word, text)
    return translated_text

def ai_translate(text: str, client) -> str:
    from google.genai import types
    
    # Inject rules + the explicit map directly into the content generation sequence
    response = client.models.generate_content(
        model='gemini-2.5-flash',
        contents=text,
        config=types.GenerateContentConfig(
            system_instruction=get_combined_system_prompt(),
            temperature=0.0, # Complete deterministic execution to stomp out variation
        )
    )
    translated_text = response.text.strip()
    
    # Eradicate edge-case casing errors
    translated_text = re.sub(r'\bME\b', 'me', translated_text)
    def fix_pronoun_casing(m):
        return "me" if m.start() > 0 else "Me"
    translated_text = re.sub(r'\b[Mm]e\b', fix_pronoun_casing, translated_text)
    
    return translated_text

# ==============================================================================
# MAIN RUNTIME APPLICATION
# ==============================================================================
if __name__ == "__main__":
    api_key = os.environ.get("GEMINI_API_KEY")
    
    if api_key:
        try:
            from google import genai
            client = genai.Client()
            print("Nordalian System: Connected to Gemini AI Translation Engine.")
            translate_func = lambda text: ai_translate(text, client)
        except Exception as e:
            print(f"Failed to boot AI Engine ({e}). Shifting to Local Fallback.")
            translate_func = local_translate
    else:
        print("Nordalian System: No API Key detected. Running on Local Dictionary Fallback.")
        translate_func = local_translate

    print("Type 'exit' to shut down.\n")
    while True:
        user_input = input("English > ")
        if user_input.lower() == 'exit': 
            print("Tschüss!")
            break
        if not user_input.strip():
            continue
        print(f"Pidgin  > {translate_func(user_input)}\n")